import type {Metadata} from "next";
import React from "react";
import localFont from "next/font/local";
import "./globals.css";

const LINESeedJP = localFont({
  src: [
    {
      path: './fonts/LINESeedJP_OTF_Th.woff2',
      weight: '100',
      style: 'thin',
    },
    {
      path: './fonts/LINESeedJP_OTF_Rg.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/LINESeedJP_OTF_Bd.woff2',
      weight: '700',
      style: 'bold',
    }
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {children,}: Readonly<{ children: React.ReactNode; }>
) {
  return (
    <html lang="ja">
    <body className={[LINESeedJP.className].join(" ")}>
    {children}
    </body>
    </html>
  );
}
